language: node_js
node_js:
- '6'
cache:
  directories: node_modules
script:
- npm run test:coverage
- npm run codecov
after_success:
- bash ./deploy.sh
os:
- linux
- osx
env:
  global:
  - ENCRYPTION: "c7881d9cb8b5"
